version: "3.9"

services:
  site1:
    image: nginx:alpine
    container_name: site1
    volumes:
      - ./site1/default.conf:/etc/nginx/conf.d/default.conf
      - ./site1/index.html:/usr/share/nginx/html/index.html
      - ./site1/htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8081:80"
  
  site2:
    image: nginx:alpine
    container_name: site2
    volumes:
      - ./site2/default.conf:/etc/nginx/conf.d/default.conf
      - ./site2/index.html:/usr/share/nginx/html/index.html
      - ./site2/htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8082:80"
